name: Dependabot auto-merge

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"

      - name: Auto-merge
        run: gh pr merge --squash --auto "$PR_URL"
